[workspace]
resolver = "2"
members = ["ckb-mock-tx-types", "ckb-vm-bench", "ckb-x64-simulator", "spike-sys"]
exclude = ["ckb-vm-test-suite/ckb-vm"]

[workspace.package]
version = "0.200.1"
license = "MIT"
edition = "2024"
authors = ["Nervos Core Dev <dev@nervos.org>"]

[workspace.dependencies]
# CKB dependencies
# ckb-jsonrpc-types = "=0.200.0"
# ckb-traits = "=0.200.0"
# ckb-types = "=0.200.0"

ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", rev = "99cd201" }
ckb-traits = { git = "https://github.com/nervosnetwork/ckb", rev = "99cd201" }
ckb-types = { git = "https://github.com/nervosnetwork/ckb", rev = "99cd201" }

ckb-vm = "=0.24.14"

# Crates defined in current workspace
ckb-mock-tx-types = { path = "ckb-mock-tx-types", version = "0.200.1" }
ckb-x64-simulator = { path = "ckb-x64-simulator", version = "0.200.1" }
spike-sys = { path = "spike-sys", version = "0.200.1" }

# Other common crates
criterion = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
