name: test-suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install ckb contract toolchain
      run: curl -f https://raw.githubusercontent.com/xxuejie/ckb-contract-toolchains/main/install.sh | bash
    - name: Install llvm 15
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 15
    - name: Clone test suite
      run: git clone https://github.com/xxuejie/ckb-vm-contrib-test-suite && cd ckb-vm-contrib-test-suite && git checkout a7c3ff05afb349db5ed7424a2da765d5c719647b && git submodule update --init --recursive
    - name: Run test suite
      run: cd ckb-vm-contrib-test-suite && ln -s .. ckb-vm-contrib && ./test.sh
